### ISSUE TITLE
Transifex native not working in combination with Django 3.x due to deprecated access

### ISSUE THREAD

**Issue by esskaey** [transifex/transifex-python#49]
**Steps to reproduce:**
- Install Django version 3.x or above
- Install transifex python
- Integrate using the steps in [https://docs.transifex.com/django-sdk/quickstart-1](url) 
- try to perform 
`./manage.py transifex push`
- The command returns error as the accessed information is deprecated since django 2.1+ 

**Uses**
- Updating the accessed variables to allow usage with recent django versions would help in better adoption

**Changes**

- transifex/native/django/management/commands/transifex.py
  `from django.core.management import BaseCommand
   from django.core.management.base import CommandParser`

- transifex/native/django/templatetags/transifex.py
  old:
  `from django.template.base import (BLOCK_TAG_END, BLOCK_TAG_START,
                                    COMMENT_TAG_END, COMMENT_TAG_START,
                                    TOKEN_BLOCK, TOKEN_COMMENT, TOKEN_TEXT,
                                    TOKEN_VAR, VARIABLE_TAG_END,
                                    VARIABLE_TAG_START)
  from django.template.defaulttags import token_kwargs`

  new:
  `import django.template.base as base`
  `from django.template.base import (BLOCK_TAG_END, BLOCK_TAG_START,
                                    COMMENT_TAG_END, COMMENT_TAG_START,
                                    VARIABLE_TAG_END, VARIABLE_TAG_START)`
  eg: TOKEN_VAR accessed as 
  `base.TokenType.VAR`
  similarly for TOKEN_BLOCK, TOKEN_COMMENT, TOKEN_TEXT, etc.
  - Similarly for token_kwargs, imported from base as  `base.token_kwargs`

**Comment by dbendilas** [comment]
@eeskaey thank you for input on this, we really appreciate it!

We've just released version [0.7.0](https://github.com/transifex/transifex-python/releases/tag/0.7.0), that includes support for Django 3.x. Feel free to test it in your project. We'd really appreciate any additional feedback you might have!
