### ISSUE TITLE
transifex_api.ResourceTranslationsAsyncDownload.download fails with missing attributes error

### ISSUE THREAD

**Issue by mkarolin** [transifex/transifex-python#62]
Apologies if I am missing something obvious, but I was following examples given in https://github.com/transifex/transifex-python/blob/devel/transifex/api/README.md#file-uploads-and-downloads.

Steps to reproduce:

<pre>
>>> from transifex.api import transifex_api
>>> transifex_api.setup(auth='my_token')
>>> org = transifex_api.Organization.get(slug='my_org')
>>> proj = org.fetch('projects').get(slug='my_project')
>>> lang = transifex_api.Language.get(code='am')
>>> resource = proj.fetch('resources').get(slug='my_resource')
>>> url = transifex_api.ResourceTranslationsAsyncDownload.download(resource=resource, language=lang)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\transifex\api\__init__.py", line 19, in download
    download = cls.create(*args, **kwargs)
  File "c:\Python27\lib\site-packages\transifex\api\jsonapi\resources.py", line 480, in create
    instance._save_new()
  File "c:\Python27\lib\site-packages\transifex\api\jsonapi\resources.py", line 415, in _save_new
    json={'data': payload})
  File "c:\Python27\lib\site-packages\transifex\api\jsonapi\apis.py", line 216, in request
    raise exc
transifex.api.jsonapi.exceptions.JsonApiException: (400, [u"&lt;JsonApiError: invalid - 'attributes' is a required property&gt;"])
</pre>

**Comment by mkarolin** [comment]
Supplying the required attributes listed in https://transifex.github.io/openapi/index.html#tag/Resource-Strings/paths/~1resource_strings_async_downloads/post 
<pre>
url = transifex_api.ResourceTranslationsAsyncDownload.download(resource=resource, language=lang,
    content_encoding = 'text',  file_type = 'default', pseudo = False)
</pre>
works, but it would be nice if the examples in the README worked out of the box.

**Comment by kbairak** [comment]
Hey @mkarolin . I'm sorry that I didn't notice this issue on time. I'm also glad you figured it out.

The same issue was reported by another user (https://github.com/transifex/transifex-python/issues/63). It has now been fixed on the API side. So, now, you can download language files with only the `resource` and `language` arguments.

**Comment by mkarolin** [comment]
Hi @kbairak, thanks for following up and for fixing the API 👍
