### ISSUE TITLE
Unable to pull from today

### ISSUE THREAD

**Issue by sbrunner** [transifex/transifex-python#72]
Hello,

From today when I do
```
tx pull -l fr --force --mode=reviewed
```
I get
```
tx INFO: Pulling translations for resource ngeo.ngeo-2_7 (source: .build/locale/ngeo.pot)
tx ERROR: invalid literal for int() with base 10: '100.0'
```

It looks like that there is an issue on the server side?

**Comment by codegaze** [comment]
Hello @sbrunner! Thank for bringing this to our attention, although I believe this message was meant for the python cli. :)

There was indeed an issue yesterday which was resolved. Here is the related repo issue https://github.com/transifex/transifex-client/issues/339, so I will close this one.

**Comment by sbrunner** [comment]
I confirm, Thanks :-)
