### ISSUE TITLE
[Django] Can't translate models.TextChoices enum values

### ISSUE THREAD

**Issue by haroal** [transifex/transifex-python#79]
Hi!

I recently subscribed to Transifex, and I have a small issue when using the `transifex-python` library in my Django project.

### Description

I have a `models.TextChoices` enum, and I want to translate the values thanks to Transifex Native.
Basically, I have that:

```python
from django.db import models
from transifex.native.django import lazyt as _

class PossibleValues(models.TextChoices):
    VALUE_A = 'value_a', _('Value A')
    VALUE_B = 'value_b', _('Value B')
    VALUE_C = 'value_c', _('Value C')
```

When I run my code (starting the Django server for instance), I have this error:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "apps/app/choices.py", line 6, in <module>
    class PossibleValues(models.TextChoices):
  File "lib/python3.8/site-packages/django/db/models/enums.py", line 28, in __new__
    cls = super().__new__(metacls, classname, bases, classdict, **kwds)
  File "/usr/lib/python3.8/enum.py", line 243, in __new__
    enum_member = __new__(enum_class, *args)
TypeError: str() argument 2 must be str, not LazyString
```

### Remarks

**Remark 1:** I previously used Django integrated i18n module (importing `from django.utils.translation import gettext_lazy as _` instead) and it was working.

**Remark 2:** If I use `from transifex.native.django import t as _` instead of the lazy version, I still have an error, even if it makes sense this time:

```
Traceback (most recent call last):
  [...]
  File "apps/app/choices.py", line 6, in <module>
    class PossibleValues(models.TextChoices):
  File "apps/app/choices.py", line 9, in PossibleValues
    VALUE_A = 'value_a', _('Value A')
  File "lib/python3.8/site-packages/transifex/native/django/utils/__init__.py", line 24, in translate
    return tx.translate(
  File "lib/python3.8/site-packages/transifex/native/core.py", line 100, in translate
    self._check_initialization()
  File "lib/python3.8/site-packages/transifex/native/core.py", line 234, in _check_initialization
    raise NotInitializedError(
transifex.native.core.NotInitializedError: TxNative is not initialized, make sure you call init() first.
```

So I HAVE to use the lazy method.

### Versions

- Python 3.8
- Django 3.2
- transifex-python 3.0.1
- Linux 5.14 x86_64 / Ubuntu 20.04

### Questions

It looks like having a `LazyString` instance as its value makes the `models.TextChoices` class unhappy (which is basically an `enum.Enum` subclass).

- Is it a known issue?
- Is there a way to translate `models.TextChoices` value with Transifex?
- Is there a workaround?

Thank you!

**Comment by haroal** [comment]
As a first hint, it looks like making `LazyString` inherit from `str` solves it. A bit hacky though, and I'm still curious to know if there is a known solution as using these `models.TextChoices` is quite basic in Django :)
Thanks!

**Comment by kbairak** [comment]
Hey @haroal,

Thank you for reporting this issue. I will admit that the lazy aspect of django translations is tricky and we will look into it.

I have two questions that can help us figure this out sooner:

1. What version of Python and Django are you using?

2. Will your project work if, insead of a `models.TextChoices` class, you use a sequence of 2-tuples?

   That is, if instead of writing:

   ```python
   from django.db import models
   from transifex.native.django import lazyt as _

   class PossibleValues(models.TextChoices):
       VALUE_A = 'value_a', _('Value A')
       VALUE_B = 'value_b', _('Value B')
       VALUE_C = 'value_c', _('Value C')

   class MyModel(models.Model):
       field = TextField(choices=PossibleValues.choices, default=PossibleValues.VALUE_A)
   ```

   You write:

   ```python
   from django.db import models
   from transifex.native.django import lazyt as _

   FieldChoices = (
       ('value_a', _('Value A')),
       ('value_b', _('Value B')),
       ('value_c', _('Value C')),
   )

   class MyModel(models.Model):
       field = TextField(choices=FieldChoices, default='value_a')
   ```

   Will it work?

   This is not to say that since there is a working alternative, you should use it and we will not bother making `TextField` work, but it will help us understand the situation better.

**Comment by haroal** [comment]
Hi @kbairak,

Thanks for you answer.

1. I gave my versions in the issue description:

> Python 3.8
Django 3.2
transifex-python 3.0.1
Linux 5.14 x86_64 / Ubuntu 20.04

2. Indeed using a sequence of 2-tuples works. However, I still need to use `models.TextChoices` for my project because I have methods/properties bound to this enum... :/ And I can't do the same with a sequence of 2-tuples.

**Comment by haroal** [comment]
Hi @kbairak,

I don't if it would help you, but just to let you know, I forked this project and fixed this with this commit: https://github.com/haroal/transifex-python/commit/03fe7a544a507ce97c3f2953df746fd5e7109b4e

If it's OK, I can even create a PR to propose these changes into your code base.

**Comment by kbairak** [comment]
Thanks @haroal for your assistance.

This was bugging me so, during the weekend, I came up with an alternative and, I think, more complete version of lazy strings.

https://gist.github.com/kbairak/ee2b7d240e1784dc2c4a3463416e5497

I will give it a try with transifex-python and django's `models.TextChoices` to see if it works. If it doesn't, we can fallback to your implementation.

**Comment by kbairak** [comment]
Hey @haroal,

I packaged it into a pull request (#80 ) and tested it on a sample django project. Would you like to give it a try on your end before we move forward on our end?

Thanks!

**Comment by haroal** [comment]
@kbairak It works! :tada: 
Just, I think you should override `__repr__` too because, else, `LazyString` are always represented by an empty string (`''`) and it's quite confusing when using it in console.
Many thanks! Just waiting for this to be merged now.

**Comment by kbairak** [comment]
@haroal I think it's not that simple with __repr__. Somehow repr's return value gets inserted into the generated migration files. I will look into it and get back to you, but my initial thought is that we may have to enhance the lazy strings with fallback values somehow. I'll let you know what I find.

**Comment by kbairak** [comment]
Yep, as I feared. This is what the migration file looks like with my initial `__repr__` implementation:

![image](https://user-images.githubusercontent.com/1336464/178676621-50f1369a-13b1-48c1-8377-b98ec188da69.png)

Without `__repr__`, it falls back to `__str__` and the migration file looks like this:

![image](https://user-images.githubusercontent.com/1336464/178683744-05dab7d0-5c79-433e-843d-1eba68350ea5.png)

I find it risky that Django dumps the output of `__repr__` into a python file and expects it to work, but what can you do?

We could go with the second solution since choices validation are in the migration file **in case** the database can enforce the validation, but most databases don't, but I don't like this. I would like the migration files to have the source version of the strings. Trying to figure out an elegant way to achieve this.

**Comment by kbairak** [comment]
@haroal That's almost exactly what I ended up doing (the only difference being is that the fallback value is optional). I will get an approval from my team and merge this.

Again, thanks so much for your help and feeback.

**Comment by haroal** [comment]
HI @kbairak,

Do you have any news about merging your new LazyString implementation? I still need it to translate my enums :)

Thanks!

**Comment by kbairak** [comment]
Hello @haroal,

The branch was just merged. Sorry this took longer than expected but the code does tricky things and required some thorough testing for us to be as confident as possible that it wouldn't introduce any bugs.

Again, thank you for bringing this issue to our attention.

**Comment by haroal** [comment]
HI @kbairak,

Thank you for all!
Could you give me an estimated time of release, please?

**Comment by kbairak** [comment]
@haroal The latest release (3.0.2) includes this fix. Thank you for you patience and help.
