### ISSUE TITLE
Tests is installed as package 

### ISSUE THREAD

**Issue by Meret6832** [transifex/transifex-python#88]
When installing the package with pip, two packages are actually installed: *transifex* and *tests* (the latter containing the tests for the package). This might slows down the installation, takes up more space, and might create conflicts with any other *tests* modules.

The *tests* package can be prevented from being built and installed by a small change in setup.py (see PR #87)

**Comment by besfahbod** [comment]
And a second PR for it: https://github.com/transifex/transifex-python/pull/90

**Comment by nbasili** [comment]
Fix released on version `3.0.3`
